apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auspost-devops-demo
  namespace: auspost-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auspost-devops-demo
